name: GitHub Metrics

on:
  schedule:
    - cron: "0 */12 * * *"   # update 2x sehari
  workflow_dispatch:          # bisa jalanin manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SmillingSword
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          filename: metrics.svg
          output_action: commit
          committer_message: "chore(metrics): update"

          # === Plugin yang keren ala hacker ===
          plugins: |
            isocalendar
            languages
            topics
            habits
            achievements

          # Opsi plugin (boleh sesuaikan)
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_topics: yes
          plugin_topics_limit: 12
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
